// <auto-generated />
using HotelListing.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HotelListing.Api.Migrations
{
    [DbContext(typeof(HotelListingDbContext))]
    [Migration("20250803210456_SeededCountriesAndHotels")]
    partial class SeededCountriesAndHotels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HotelListing.Api.Data.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CountryId");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Cananda",
                            ShortName = "CAN"
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "England",
                            ShortName = "ENG"
                        });
                });

            modelBuilder.Entity("HotelListing.Api.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Toronto",
                            CountryId = 1,
                            Name = "Marriot Hotel",
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Whistler",
                            CountryId = 1,
                            Name = "Fairmont Chateau Whistler",
                            Rating = 4.7000000000000002
                        },
                        new
                        {
                            Id = 3,
                            Address = "Birmingham",
                            CountryId = 2,
                            Name = "The Grand Hotel Birminham",
                            Rating = 4.5999999999999996
                        },
                        new
                        {
                            Id = 4,
                            Address = "London",
                            CountryId = 2,
                            Name = "Hampton by Hilton London Stanstead",
                            Rating = 4.2999999999999998
                        });
                });

            modelBuilder.Entity("HotelListing.Api.Data.Hotel", b =>
                {
                    b.HasOne("HotelListing.Api.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("HotelListing.Api.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });
#pragma warning restore 612, 618
        }
    }
}
